<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BolBsRaw extends Model
{
    use HasFactory;

    protected $table = 'bol_bs_raw';

    public $timestamps = false;

    protected $fillable = [
        'company_id',
        'company_name',
        'year',
        'assets',
        'cash_and_deposits_at_financial_institutions',
        'accounts_receivable',
        'accounts_and_notes_receivable_net',
        'total_short_term_loans_consolidation',
        'inventories_net',
        'accrued_income',
        'prepaid_expenses',
        'other_current_assets',
        'others_total_current_assets',
        'total_current_assets',
        'total_long_term_loans_and_investments',
        'property_plant_and_equipment_net',
        'other_non_current_assets',
        'others_total_non_current_assets',
        'total_non_current_assets',
        'total_assets',
        'liabilities_and_shareholders_equity',
        'liabilities',
        'bank_overdrafts_and_short_term_loans_from_financial_institutions',
        'accounts_payable',
        'total_accounts_payable_and_notes_payable',
        'current_portion_of_long_term_loans',
        'total_short_term_loans',
        'accrued_expenses',
        'unearned_revenues',
        'other_current_liabilities',
        'others_total_current_liabilities',
        'total_current_liabilities',
        'total_long_term_loans',
        'other_non_current_liabilities',
        'others_total_non_current_liabilities',
        'total_non_current_liabilities',
        'total_liabilities',
        'shareholders_equity',
        'authorized_preferred_stocks',
        'authorized_common_stocks',
        'issued_and_paid_up_preferred_stocks',
        'issued_and_paid_up_common_stocks',
        'appraisal_surplus_on_property_plant_and_equipment',
        'accumulated_retained_earnings',
        'others',
        'total_shareholders_equity',
        'total_liabilities_and_shareholders_equity',
        'additional_information_for_shareholders_equity',
        'common_stocks',
        'no_of_shares_authorized',
        'par_value_baht_authorized',
        'no_of_shares_issued_and_paid_up',
        'par_value_baht_issued_and_paid_up',
    ];

    protected $casts = [
        'year' => 'integer',
        'assets' => 'decimal:2',
        'cash_and_deposits_at_financial_institutions' => 'decimal:2',
        'accounts_receivable' => 'decimal:2',
        'accounts_and_notes_receivable_net' => 'decimal:2',
        'total_short_term_loans_consolidation' => 'decimal:2',
        'inventories_net' => 'decimal:2',
        'accrued_income' => 'decimal:2',
        'prepaid_expenses' => 'decimal:2',
        'other_current_assets' => 'decimal:2',
        'others_total_current_assets' => 'decimal:2',
        'total_current_assets' => 'decimal:2',
        'total_long_term_loans_and_investments' => 'decimal:2',
        'property_plant_and_equipment_net' => 'decimal:2',
        'other_non_current_assets' => 'decimal:2',
        'others_total_non_current_assets' => 'decimal:2',
        'total_non_current_assets' => 'decimal:2',
        'total_assets' => 'decimal:2',
        'liabilities_and_shareholders_equity' => 'decimal:2',
        'liabilities' => 'decimal:2',
        'bank_overdrafts_and_short_term_loans_from_financial_institutions' => 'decimal:2',
        'accounts_payable' => 'decimal:2',
        'total_accounts_payable_and_notes_payable' => 'decimal:2',
        'current_portion_of_long_term_loans' => 'decimal:2',
        'total_short_term_loans' => 'decimal:2',
        'accrued_expenses' => 'decimal:2',
        'unearned_revenues' => 'decimal:2',
        'other_current_liabilities' => 'decimal:2',
        'others_total_current_liabilities' => 'decimal:2',
        'total_current_liabilities' => 'decimal:2',
        'total_long_term_loans' => 'decimal:2',
        'other_non_current_liabilities' => 'decimal:2',
        'others_total_non_current_liabilities' => 'decimal:2',
        'total_non_current_liabilities' => 'decimal:2',
        'total_liabilities' => 'decimal:2',
        'shareholders_equity' => 'decimal:2',
        'authorized_preferred_stocks' => 'decimal:2',
        'authorized_common_stocks' => 'decimal:2',
        'issued_and_paid_up_preferred_stocks' => 'decimal:2',
        'issued_and_paid_up_common_stocks' => 'decimal:2',
        'appraisal_surplus_on_property_plant_and_equipment' => 'decimal:2',
        'accumulated_retained_earnings' => 'decimal:2',
        'others' => 'decimal:2',
        'total_shareholders_equity' => 'decimal:2',
        'total_liabilities_and_shareholders_equity' => 'decimal:2',
        'additional_information_for_shareholders_equity' => 'decimal:2',
        'common_stocks' => 'decimal:2',
        'no_of_shares_authorized' => 'integer',
        'par_value_baht_authorized' => 'decimal:2',
        'no_of_shares_issued_and_paid_up' => 'integer',
        'par_value_baht_issued_and_paid_up' => 'decimal:2',
    ];
}
