<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BolFinancial extends Model
{
    protected $table = 'bol_financial';
    protected $primaryKey = 'id';
    public $incrementing = true;
    protected $keyType = 'int';

    public $timestamps = true;

    protected $fillable = [
        'registration_no',
        'fiscal_year',
        'financial_date',
        'fs_type',
        'total_assets',
        'short_term_loans_in_liabilities',
        'long_term_loans_in_liabilities',
        'retained_earning',
        'total_revenue',
        'gross_profit',
        'income_before_depreciation',
        'income_before_interest_and_income_taxes',
        'net_income',
        'account_receivable',
        'account_notes_receivable_net',
        'inventories',
        'short_term_loans_assets',
        'total_current_assets',
        'long_term_loans_assets',
        'property_plant_equipment_net',
        'total_non_current_assets',
        'cash_and_deposits_at_financial_institutions',
        'accounts_payable',
        'total_current_liabilities',
        'total_non_current_liabilities',
        'total_liabilities',
        'authorized_common_stocks',
        'issued_paid_up_common_stocks',
        'total_shareholders_equity',
        'total_liabilities_shareholders_equity',
        'net_sales',
        'cost_of_sales_services',
        'operating_expenses',
        'earnings_loss_per_share',
        'short_term_loan',
        'interest_expenses',
        'current_ratio',
        'quick_ratio',
        'accounts_receivable_turnover',
        'accounts_payable_turnover',
        'average_payment_period',
        'inventory_turnover',
        'collection_period',
        'day_sales_inventory',
        'gross_profit_margin_percent',
        'net_profit_margin_percent',
        'roa',
        'roe',
        'debt_ratio',
        'debt_equity_ratio',
        'interest_coverage',
        'net_sales_growth_percent',
        'total_revenue_growth_percent',
        'net_profit_growth_percent',
        'total_asset_growth_percent',
    ];

    protected $casts = [
        'financial_date'                           => 'date',
        'total_assets'                              => 'decimal:2',
        'short_term_loans_in_liabilities'           => 'decimal:2',
        'long_term_loans_in_liabilities'            => 'decimal:2',
        'retained_earning'                          => 'decimal:2',
        'total_revenue'                             => 'decimal:2',
        'gross_profit'                              => 'decimal:2',
        'income_before_depreciation'                => 'decimal:2',
        'income_before_interest_and_income_taxes'   => 'decimal:2',
        'net_income'                                => 'decimal:2',
        'account_receivable'                        => 'decimal:2',
        'account_notes_receivable_net'              => 'decimal:2',
        'inventories'                               => 'decimal:2',
        'short_term_loans_assets'                   => 'decimal:2',
        'total_current_assets'                      => 'decimal:2',
        'long_term_loans_assets'                    => 'decimal:2',
        'property_plant_equipment_net'              => 'decimal:2',
        'total_non_current_assets'                  => 'decimal:2',
        'cash_and_deposits_at_financial_institutions' => 'decimal:2',
        'accounts_payable'                          => 'decimal:2',
        'total_current_liabilities'                 => 'decimal:2',
        'total_non_current_liabilities'             => 'decimal:2',
        'total_liabilities'                         => 'decimal:2',
        'authorized_common_stocks'                  => 'decimal:2',
        'issued_paid_up_common_stocks'              => 'decimal:2',
        'total_shareholders_equity'                 => 'decimal:2',
        'total_liabilities_shareholders_equity'     => 'decimal:2',
        'net_sales'                                 => 'decimal:2',
        'cost_of_sales_services'                    => 'decimal:2',
        'operating_expenses'                        => 'decimal:2',
        'earnings_loss_per_share'                   => 'decimal:2',
        'short_term_loan'                           => 'decimal:2',
        'interest_expenses'                         => 'decimal:2',
        'current_ratio'                             => 'decimal:2',
        'quick_ratio'                               => 'decimal:2',
        'accounts_receivable_turnover'              => 'decimal:2',
        'accounts_payable_turnover'                 => 'decimal:2',
        'average_payment_period'                    => 'decimal:2',
        'inventory_turnover'                        => 'decimal:2',
        'collection_period'                         => 'decimal:2',
        'day_sales_inventory'                       => 'decimal:2',
        'gross_profit_margin_percent'               => 'decimal:2',
        'net_profit_margin_percent'                 => 'decimal:2',
        'roa'                                       => 'decimal:2',
        'roe'                                       => 'decimal:2',
        'debt_ratio'                                => 'decimal:2',
        'debt_equity_ratio'                         => 'decimal:2',
        'interest_coverage'                         => 'decimal:2',
        'net_sales_growth_percent'                  => 'decimal:2',
        'total_revenue_growth_percent'              => 'decimal:2',
        'net_profit_growth_percent'                 => 'decimal:2',
        'total_asset_growth_percent'                => 'decimal:2',
        'created_at'                                => 'datetime',
        'updated_at'                                => 'datetime',
    ];
}
